[package]
name = "discord-gating-bot"
version = "0.1.0"
edition = "2021"
license = "GPLv3"
description = """A discord bot that can grant discord roles on a server based on reputation in a specific colony"""
readme = "README.md"
authors =["Hans Mündelein <hans@muendelein.me>", "Christian Maniewski <code@chmanie.com>"]
categories = ["colony"]

[features]
default = ["completion"]
completion = ["dep:clap_complete"]
build_info = ["dep:shadow-rs"]

[dependencies]
actix-web = { version = "4.3.0", features = ["rustls"] }
anyhow = "1.0.69"
bincode = "1.3.3"
chacha20poly1305 = "0.10.1"
clap = { version = "3.2.15", features = ["cargo", "derive"] }
clap_complete = { version = "3.2.3", optional = true }
confique = "0.2.2"
hex = "0.4.3"
once_cell = "1.13.0"
serde = { version = "1.0.142", features = ["derive"] }
serde_derive = "1.0.142"
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
shadow-rs = { version = "0.16.1", optional = true }
sled = "0.34.7"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.36", features = ["release_max_level_info"] }
tracing-appender = "0.2.2"
tracing-log = "0.1.3"
tracing-subscriber = "0.3.15"

[build-dependencies]
clap = { version = "3.2.15", features = ["cargo", "derive"] }
clap-verbosity-flag = "1.0.1"
clap_complete = "3.2.3"
clap_mangen = "0.1.10"
confique = "0.2.2"
once_cell = "1.13.0"
serde = { version = "1.0.142", features = ["derive"] }
serde_derive = "1.0.142"
shadow-rs = { version = "0.16.1", optional = true }
tracing-log = "0.1.3"

