.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH discord-gating-bot 1  "discord-gating-bot 0.1.0" 
.SH NAME
discord\-gating\-bot \- A discord bot that can grant discord roles on a server based on reputation in a specific colony
.SH SYNOPSIS
\fBdiscord\-gating\-bot\fR [\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fB\-c\fR|\fB\-\-config\-file\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-q\fR|\fB\-\-quiet\fR] [\fB\-t\fR|\fB\-\-token\fR] [\fB\-s\fR|\fB\-\-shards\fR] [\fB\-h\fR|\fB\-\-host\fR] [\fB\-p\fR|\fB\-\-port\fR] [\fB\-\-cert\fR] [\fB\-k\fR|\fB\-\-key\fR] [\fB\-\-acme\-endpoint\fR] [\fB\-\-acme\-port\fR] [\fB\-\-directory\fR] [\fB\-\-staging\-directory\fR] [\fB\-\-staging\fR] [\fB\-\-encryption\-key\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
.PP
Running the bot binary without any sub command will start an http server,
connect to discord and listen for commands. 
.PP
By default the bot will store all data encrypted in an embedded database. 
Most of the action will happens via the slash commands from discord and the 
following redirects to the http server. 
.PP
The bot can be configured via a config file, environment variables or 
command line arguments. 
.PP
Other sub commands are used offline to help with certain
operations, e.g. key generation and most importantly the slash command 
registration. 
.PP
When running the bot for the first time, no slash commands are 
registered for the discord application, which makes the bot pretty useless.
With the `register` sub command, the bot will register all slash commands either
globally or for a specific guild. Global registration may take some time to 
propagate, while guild registration is instant. 
.PP
.PP
.SH OPTIONS
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.TP
\fB\-c\fR, \fB\-\-config\-file\fR=\fIFILE\fR
Sets a custom config file
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Define the verbosity of the application, repeat for more verbosity
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Supress all logging
.TP
\fB\-t\fR, \fB\-\-token\fR=\fITOKEN\fR
The discord bot token
.TP
\fB\-s\fR, \fB\-\-shards\fR=\fISHARDS\fR
The number of guild shards
.TP
\fB\-h\fR, \fB\-\-host\fR=\fIHOST\fR
The address to listen on
.TP
\fB\-p\fR, \fB\-\-port\fR=\fIPORT\fR
The port to listen on
.TP
\fB\-\-cert\fR=\fIFILE\fR
The path to the certificate File
.TP
\fB\-k\fR, \fB\-\-key\fR=\fIFILE\fR
The path to the private key File
.TP
\fB\-\-acme\-endpoint\fR=\fIACME_ENDPOINT\fR
The address of the acme server to use
.TP
\fB\-\-acme\-port\fR=\fIACME_PORT\fR
The port to listen on
.TP
\fB\-\-directory\fR=\fIDIR\fR
The path to the directory where the certificates are stored
.TP
\fB\-\-staging\-directory\fR=\fIDIR\fR
The path to the directory where the certificates are stored
.TP
\fB\-\-staging\fR=\fIDIR\fR
The path to the directory where the certificates are stored
.TP
\fB\-\-encryption\-key\fR=\fIENCRYPTION_KEY\fR
The encryption key to use for the database and session tokens
.SH SUBCOMMANDS
.TP
discord\-gating\-bot\-completion(1)
Generates completion scripts for the specified shell
.TP
discord\-gating\-bot\-config(1)
Print or edit the configuration
.TP
discord\-gating\-bot\-key(1)
Generate an encrypted key
.TP
discord\-gating\-bot\-discord(1)
Interact with discord directly
.TP
discord\-gating\-bot\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.1.0
.SH AUTHORS
Hans Mündelein <hans@muendelein.me>
Christian Maniewski <code@chmanie.com>
