.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH discord-gating-bot 1  "discord-gating-bot 0.1.0" 
.SH NAME
discord\-gating\-bot \- A discord bot that can grant discord roles on a server based on reputation in a specific colony
.SH SYNOPSIS
\fBdiscord\-gating\-bot\fR [\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fB\-c\fR|\fB\-\-config\-file\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-q\fR|\fB\-\-quiet\fR] [\fB\-t\fR|\fB\-\-token\fR] [\fB\-i\fR|\fB\-\-invite\-url\fR] [\fB\-h\fR|\fB\-\-host\fR] [\fB\-u\fR|\fB\-\-url\fR] [\fB\-p\fR|\fB\-\-port\fR] [\fB\-d\fR|\fB\-\-directory\fR] [\fB\-s\fR|\fB\-\-storage\-type\fR] [\fB\-k\fR|\fB\-\-key\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
.PP
Running the bot without any sub command will start an http server,
connect to discord and listen for commands, all with the default configuration.
.PP
Running the bot for the first time, you probably want to generate an encryption
key and register the discord slash commands with the `storage` and `discord`
subcommands.
.PP
.PP
.SH OPTIONS
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.TP
\fB\-c\fR, \fB\-\-config\-file\fR=\fIFILE\fR
Sets a custom config file
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Define the verbosity of the application, repeat for more verbosity
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Supress all logging
.TP
\fB\-t\fR, \fB\-\-token\fR=\fITOKEN\fR
The discord bot token
.TP
\fB\-i\fR, \fB\-\-invite\-url\fR=\fIINVITE_URL\fR
The discor bot invitation url
.TP
\fB\-h\fR, \fB\-\-host\fR=\fIHOST\fR
The address to listen on
.TP
\fB\-u\fR, \fB\-\-url\fR=\fIURL\fR
The base url under which the server is reachable
.TP
\fB\-p\fR, \fB\-\-port\fR=\fIPORT\fR
The port to listen on
.TP
\fB\-d\fR, \fB\-\-directory\fR=\fIDIRECTORY\fR
The path where the persistent data is stored
.TP
\fB\-s\fR, \fB\-\-storage\-type\fR=\fISTORAGE_TYPE\fR
How to store data, on disk or in memory
.TP
\fB\-k\fR, \fB\-\-key\fR=\fIKEY\fR
The encryption_key used to encrypt the stored data
.SH SUBCOMMANDS
.TP
discord\-gating\-bot\-config(1)
Print the configuration and get a template file
.TP
discord\-gating\-bot\-storage(1)
Interact with the presistent storage and encryption
.TP
discord\-gating\-bot\-discord(1)
Interact with discord directly, e.g. register slash commands
.TP
discord\-gating\-bot\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.1.0
.SH AUTHORS
Hans Mündelein <hans@muendelein.me>
Christian Maniewski <code@chmanie.com>
