permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
name: check

jobs:
  # check if code is correclty formatted
  fmt:
    runs-on: ubuntu-latest
    name: ubuntu / stable / fmt
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: cargo fmt --check
        run: cargo fmt --check --all

  clippy:
    runs-on: ubuntu-latest
    name: ubuntu / ${{ matrix.toolchain }} / clippy
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta, nightly ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: Build frontend
        run: cd frontend && npm install && npm run build && cd -
      - name: cargo clippy
        uses: actions-rs-plus/clippy-check@v2
